on: push
jobs:
  scan:
    strategy:
      matrix:
        owner: [iterative, eslint]
        host: [api.travis-ci.com, api.travis-ci.org]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          pip install .
          travieso ${{ matrix.owner }} --host=${{ matrix.host }} --output=data
          docker run -iv "$PWD/data:/data" trufflesecurity/trufflehog filesystem --directory=/data
      - uses: actions/upload-artifact@v3
        with:
          name: data
          path: data
